### ISSUE TITLE
"Unknown Human Player" in Name Field w/ 0 Turns (Stats Screen)

### ISSUE THREAD

**Issue by giygas73** [HearthStats/HearthStats.net-Uploader#621]
Hey, love the program, but recently I have been seeing "UNKNOWN HUMAN PLAYER" appear in the stats window. The "turns" goes to 0 also, but the win/lose condition is recorded correctly. I cannot attribute this to anything, it appears to happen a lot when playing against warlocks though but I have also seen it with druid and priest (it happens rarely, but still enough to be annoying, especially when some of my decks are important in number of turns and I review games sometimes and stuff to see if there is any correlation between number of turns and my win condition (mainly this is dealing with my Fatigue Mage, but also I like to examine if number of turns does anything with my Control Warrior as well).

The earliest I see this occuring in my logs is Jan 9th 22:48 (against a Priest) and since then it happens in something like 1-5% of my games.

Here is a screenshot of what I am talking about: https://imgur.com/lazamhA

Would be great if you could figure out why this is occurring for me. I believe the app auto-updated on that day, so perhaps something in the release that came out around Jan 9th had some sort of bug? The only weird thing, is there does not appear to be any other issue here for this yet, so perhaps this is something with my specific setup. Let me know what you need in terms of logs and stuff and I can try to provide that.

Thanks :)

**Comment by tyrcho** [comment]
I can confirm this issue, it occurs maybe 1-2% of the games for me also, and was also reported informally. I'll investigate it for sure when I reproduce it, it's related to some pattern in the log file I guess.

About the screenshot you posted, it seems to be from a concurrent tracking tool, no ?

**Comment by trigun0x2** [comment]
Well makes sense why he kept his code close sourced and it worked super well. He's been using log parsing for a while now.

**Comment by giygas73** [comment]
Sorry I'm just realizing now I think I may have somehow made this under the wrong github?! (hearthstone deck tracker vs hearthstats) or are these the same thing? Sorry just a lil confused cause I've never heard of hearthstats but I do use "hearthstone deck tracker", could have sworn I opened this issue under there but I may have mixed something up, haha. Good to hear that I'm not the only one with this bug though. Not sure what you mean by "concurrent", care to elaborate?

Thanks!!

**Comment by giygas73** [comment]
Yeah so it looks like I guess this is in the wrong github, I really have no idea how I mixed this up sorry I'm kinda new to Github haha. I'll close this one off and add the ticket to the proper github project for the program I am dealing with, which is here: https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/new
