### ISSUE TITLE
Companion closing after match starts

### ISSUE THREAD

**Issue by lexblow** [HearthStats/HearthStats.net-Uploader#641]
My companion is closing every single time after match starts on the mullingan phase.it detects my deck, me and my opponent, the overlay is shown until mullingan phase, when the companion closes, and so the overlay. PLease HELP!

**Comment by trigun0x2** [comment]
Hey @lexblow can you try disabling the video feature in the options page?

**Comment by lexblow** [comment]
Yes i can, and yes i tried, and Yes! IT WORKED!!
And YES, THANK YOU!!!!!

**Comment by trigun0x2** [comment]
Awesome! :)
