### ISSUE TITLE
OS X: Deck overlay disappears after match and doesn't come back up

### ISSUE THREAD

**Issue by slapner** [HearthStats/HearthStats.net-Uploader#650]
In the latest version, after each match your deck overlay disappears and does not reappear when the match starts. The opponents deck list pops up each match but your own does not. The only way to get it to show is to toggle between decks between each match which is pretty annoying and easy to forget.

**Comment by jazbek** [comment]
I am having this problem also.

**Comment by trigun0x2** [comment]
This is already fixed and a new release will be pushed tomorrow.
