### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by Bananemitmayo** [HearthStats/HearthStats.net-Uploader#654]
Since the new update iam unable to use HearthStats Companion because i cant login.
It just nothing happens but if i type in a wrong Username or password it says Invalid Email or Password. Anyone know what to do? Thank you guys

**Comment by brbrainerd** [comment]
Same issue.  I was using the Companion regularly a couple of months ago, and the only thing I can think of that's changed (besides the version) is that I'm using Java 8 exclusively now.

**Comment by g0tMylk** [comment]
Yeah, I have tried everything. Old Companions don't work. Very frustrating.

**Comment by Riplexus** [comment]
Can't login either, why was the login screen integrated at all btw?

**Comment by cyberjedi** [comment]
Same issue.

**Comment by trigun0x2** [comment]
Hey we are fixing this right away.

**Comment by brbrainerd** [comment]
Outstanding!  Thanks trigun0x2.

**Comment by g0tMylk** [comment]
Awesome :) it's the only problem I have had with what is an essential part of my life now! <3 Hearthstats

**Comment by trigun0x2** [comment]
<3 @g0tMylk we've reverted back to an other version of the uploader for now because our devs are on vacation today.

**Comment by g0tMylk** [comment]
I was going to say props for working on a bank holiday but wasn't sure where you guys are located :) 
Best customer service. I shall be upgrading to premium

**Comment by trigun0x2** [comment]
Hey can you guys try it now?

**Comment by cyberjedi** [comment]
I am back in business on OS X and 22.3.  Thanks for the quick turnaround.

**Comment by Bananemitmayo** [comment]
Wow thank you so much for this quick reaction it runs smooth as ever. :)

**Comment by Riplexus** [comment]
Works like a charm, thanks a lot!

**Comment by g0tMylk** [comment]
You guys are awesome. Thank you!
