### ISSUE TITLE
HearthStats uploader starts minimized, can't log in

### ISSUE THREAD

**Issue by ilCanaglia** [HearthStats/HearthStats.net-Uploader#675]
When I start HearthStats uploader it starts minimized and I can't log in. 

The icon appears in the windows bar and if I hoover above it with the mouse I can see a miniature of the log in window, but if I click the icon nothing happens. I never get the log in window up so that I can edit info or press log in. I have updated to both the latest version of Java and of the uploader but to no effect on the issue.

If anyone has a solution to this I would be very greatful.

Thanks

**Comment by trigun0x2** [comment]
Hey we have officially switched over to Hearthstone Deck Tracker. You can download here: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/download/v0.10.2/Hearthstone.Deck.Tracker-v0.10.2.zip
