### ISSUE TITLE
HDT crashes instantly after launching

### ISSUE THREAD

**Issue by Paleek** [HearthStats/HearthStats.net-Uploader#676]
If I delete all data and run the program it will open but not function properly and eventually crash. After that I can't open the application at all. Heres the Crash report:
http://pastebin.com/3p5wzWfp

**Comment by trigun0x2** [comment]
Hey @Paleek please download the latest version. It should fix this issue: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/download/v0.10.6/Hearthstone.Deck.Tracker-v0.10.6.zip

**Comment by Paleek** [comment]
I figured. But thanks for the help anyway. I advice you to update the link on hearthstats.

Date: Wed, 10 Jun 2015 07:20:46 -0700
