### ISSUE TITLE
OS X: Player Overlay Not working. Shows no cards and deck always above 32

### ISSUE THREAD

**Issue by keeyon2** [HearthStats/HearthStats.net-Uploader#680]
It does not show my deck at all in the overlay.  Just shows my hand size and that my deck always has 32 or 31 cards

**Comment by trigun0x2** [comment]
Hey is this our uploader of the HSTracker? Also can you upload a screenshot?

**Comment by keeyon2** [comment]
Hi Trigun, I was an idiot and was not using HSTracker correctly.  User Error. Thanks for the quick response as well
